name: skype
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  cloud_firestore: ^0.14.1+3

  permission_handler: ^5.0.1+1

  firebase_auth: ^0.18.1+2

  google_sign_in: ^4.5.5

  firebase_core: ^0.5.0+1

  shimmer: ^1.1.2

  gradient_app_bar: ^0.1.3

  emoji_picker: ^0.1.0

  image_picker: ^0.6.7+14

  path_provider: ^1.6.24

  firebase_storage: ^5.0.1

  image: ^2.1.19

  provider: ^4.3.2+2

  cached_network_image: ^2.3.3

  agora_rtc_engine: ^1.0.9

  hive: ^1.4.4+1

  sqflite: ^1.3.2+1

  intl: ^0.16.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/app_logo.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
